Remove Ready for testing component
specify/specify7-test-panel pull request #115
Opened 2024-04-03 17:36 UTC by CarolineDenis

Fixes #114

2024-04-04 01:55 UTC, maxpatiiuk requested changes
1. this doesn't disable the automatic deployment - it only hides them on the front-end
2. you don't need to change any code to disable automatic deployments. you just have to change this config variable:

   - Set this to 0:
      https://github.com/specify/specify7-test-panel/blob/1b150b855a20ef5f9be0bbbf3494e3734fe6438f/app/const/siteConfig.ts#L14

    - Disable the webhook that notifies test panel of changes to github:
       https://github.com/specify/specify7-test-panel/?tab=readme-ov-file#configuring-webhook

       (I have just done this)

2024-04-05 02:16 UTC, maxpatiiuk requested changes

2024-04-05 02:16 UTC, maxpatiiuk commented on app/components/Dashboard.tsx
> -      branchesWithoutPullRequests.includes(branch)
do not remove this - please revert the changes in all files except for siteConfig.ts

reason: readyForTesting is not exactly the same as automatic deployments
ready for testing means deployments on branches on which there is also a PR that is ready to be tested - regardless of whether that deployment was done automatically or not

2024-04-06 00:28 UTC, maxpatiiuk approved these changes

2024-04-08 13:28 UTC, merged

2024-04-15 18:09 UTC, CarolineDenis commented
@maxpatiiuk , 

the ready for testing component is still present on the test panel. Are you sure this was enough to do in order to remove it?

2024-04-16 03:04 UTC, maxpatiiuk commented
https://github.com/specify/specify7-test-panel/issues/114 was about "Remove automatic deployments", not about "
Remove Ready for testing component"

Automatic deployments were correctly disabled by this PR - all good.
The "Ready for testing" component does not equal "Automatic deployment". "Ready for testing" just means a deployment for a branch, that has a PR that is marked as ready for testing - regardless of whether than deployment was done manually or automatically (no more automatically as of this PR)